path_format:
  $ref: ./parameters/path/format.yml

path_issue_id:
  $ref: ./parameters/path/issue_id.yml

path_membership_id:
  $ref: ./parameters/path/membership_id.yml

path_project_id:
  $ref: ./parameters/path/project_id.yml

path_time_entry_id:
  $ref: ./parameters/path/time_entry_id.yml

path_user_id:
  $ref: ./parameters/path/user_id.yml

path_group_id:
  $ref: ./parameters/path/group_id.yml

query_limit:
  $ref: ./parameters/query/limit.yml

query_offset:
  $ref: ./parameters/query/offset.yml
