x_redmine_switch_user:
  $ref: ./parameters/header/x_redmine_switch_user.yml

x_redmine_nometa:
  $ref: parameters/header/x_redmine_nometa.yml

format:
  $ref: ./parameters/path/format.yml

limit:
  $ref: ./parameters/query/limit.yml

offset:
  $ref: ./parameters/query/offset.yml

nometa:
  $ref: ./parameters/query/nometa.yml

issue_id:
  $ref: ./parameters/path/issue_id.yml

project_id:
  $ref: ./parameters/path/project_id.yml

membership_id:
  $ref: ./parameters/path/membership_id.yml

user_id:
  $ref: ./parameters/path/user_id.yml

time_entry_id:
  $ref: ./parameters/path/time_entry_id.yml

issue_relation_id:
  $ref: ./parameters/path/issue_relation_id.yml

version_id:
  $ref: ./parameters/path/version_id.yml

wiki_page_title:
  $ref: ./parameters/path/wiki_page_title.yml

attachment_id:
  $ref: ./parameters/path/attachment_id.yml

issue_category_id:
  $ref: ./parameters/path/issue_category_id.yml

role_id:
  $ref: ./parameters/path/role_id.yml

group_id:
  $ref: ./parameters/path/group_id.yml
