openapi: 3.0.3

info:
  title: Redmine API
  description: Unofficial OpenAPI specification for the Redmine API.
  contact:
    name: d-yoshi/redmine-openapi
    url: https://github.com/d-yoshi/redmine-openapi
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.6.3

servers:
  - url: /

externalDocs:
  description: Redmine API Official Developer Guide
  url: https://www.redmine.org/projects/redmine/wiki/Rest_api

security:
  - BasicAuth: []
  - ApiKeyAuth: []

paths:
  /issues.{format}:
    $ref: ./paths/issues.yml

  /issues/{issue_id}.{format}:
    $ref: ./paths/issues.issue_id.yml

  /issues/{issue_id}/watchers.{format}:
    $ref: ./paths/issues.issue_id.watchers.yml

  /issues/{issue_id}/watchers/{user_id}.{format}:
    $ref: ./paths/issues.issue_id.watchers.user_id.yml

  /projects.{format}:
    $ref: ./paths/projects.yml

  /projects/{project_id}.{format}:
    $ref: ./paths/projects.project_id.yml

  /projects/{project_id}/archive.{format}:
    $ref: ./paths/projects.project_id.archive.yml

  /projects/{project_id}/unarchive.{format}:
    $ref: ./paths/projects.project_id.unarchive.yml

  /projects/{project_id}/memberships.{format}:
    $ref: ./paths/projects.project_id.memberships.yml

  /memberships/{membership_id}.{format}:
    $ref: ./paths/memberships.membership_id.yml

  /users.{format}:
    $ref: ./paths/users.yml

  /users/{user_id}.{format}:
    $ref: ./paths/users.user_id.yml

  /users/current.{format}:
    $ref: ./paths/users.current.yml

  /time_entries.{format}:
    $ref: ./paths/time_entries.yml

  /time_entries/{time_entry_id}.{format}:
    $ref: ./paths/time_entries.time_entry_id.yml

  /news.{format}:
    $ref: ./paths/news.yml

  /projects/{project_id}/news.{format}:
    $ref: ./paths/projects.project_id.news.yml

  /issues/{issue_id}/relations.{format}:
    $ref: ./paths/issues.issue_id.relations.yml

  /relations/{issue_relation_id}.{format}:
    $ref: ./paths/relations.issue_relation_id.yml

  /projects/{project_id}/versions.{format}:
    $ref: ./paths/projects.project_id.versions.yml

  /versions/{version_id}.{format}:
    $ref: ./paths/versions.version_id.yml

  /projects/{project_id}/wiki/index.{format}:
    $ref: ./paths/projects.project_id.wiki.index.yml

  /projects/{project_id}/wiki/{wiki_page_title}.{format}:
    $ref: ./paths/projects.project_id.wiki.wiki_page_title.yml

  /projects/{project_id}/wiki/{wiki_page_title}/{version_id}.{format}:
    $ref: ./paths/projects.project_id.wiki.wiki_page_title.version_id.yml

  /queries.{format}:
    $ref: ./paths/queries.yml

  /attachments/{attachment_id}.{format}:
    $ref: ./paths/attachments.attachment_id.yml

  /issue_statuses.{format}:
    $ref: ./paths/issue_statuses.yml

  /trackers.{format}:
    $ref: ./paths/trackers.yml

  /projects/{project_id}/issue_categories.{format}:
    $ref: ./paths/projects.project_id.issue_categories.yml

  /enumerations/issue_priorities.{format}:
    $ref: ./paths/enumerations.issue_priorities.yml

  /enumerations/time_entry_activities.{format}:
    $ref: ./paths/enumerations.time_entry_activities.yml

  /enumerations/document_categories.{format}:
    $ref: ./paths/enumerations.document_categories.yml

  /issue_categories/{issue_category_id}.{format}:
    $ref: ./paths/issue_categories.issue_category_id.yml

  /roles.{format}:
    $ref: ./paths/roles.yml

  /roles/{role_id}.{format}:
    $ref: ./paths/roles.role_id.yml

  /groups.{format}:
    $ref: ./paths/groups.yml

  /groups/{group_id}.{format}:
    $ref: ./paths/groups.group_id.yml

  /groups/{group_id}/users.{format}:
    $ref: ./paths/groups.group_id.users.yml

  /groups/{group_id}/users/{user_id}.{format}:
    $ref: ./paths/groups.group_id.users.user_id.yml

  /custom_fields.{format}:
    $ref: ./paths/custom_fields.yml

  /search.{format}:
    $ref: ./paths/search.yml

  /projects/{project_id}/files.{format}:
    $ref: ./paths/projects.project_id.files.yml

  /my/account.{format}:
    $ref: ./paths/my_account.yml

  /journals/{journal_id}.{format}:
    $ref: ./paths/journals.journal_id.yml

  /uploads.{format}:
    $ref: ./paths/uploads.yml

components:
  securitySchemes:
    $ref: ./components/securitySchemes.yml

tags:
  $ref: ./tags.yml
