type: object
required:
  - id
  - name
  - identifier
  - description
  - status
  - is_public
  - inherit_members
  - created_on
  - updated_on
properties:
  id:
    type: integer
  name:
    type: integer
  identifier:
    type: integer
  description:
    type: integer
    nullable: true
  homepage:
    type: string
    nullable: true
  parent_id:
    type: integer
  status:
    type: integer
  is_public:
    type: boolean
  inherit_members:
    type: boolean
  trackers:
    type: array
    items:
      $ref: ./IdName.yml
  issue_categories:
    type: array
    items:
      $ref: ./IdName.yml
  enabled_modules:
    type: array
    items:
      $ref: ./IdName.yml
  created_on:
    type: string
    format: date-time
  updated_on:
    type: string
    format: date-time
