name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ".github/workflows/ci.yml"
      - name: lint
        run: npx @redocly/cli lint src/openapi.yml
      - name: bundle
        run: npx @redocly/cli bundle src/openapi.yml -o openapi.yml
      - uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi.yml

  test_openapi-typescript:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ".github/workflows/ci.yml"
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: generate type file
        run: npx openapi-typescript openapi.yml -o test/dist/openapi-typescript/schema.d.ts

  commit:
    needs:
      - test_openapi-typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi.yml
          git diff-index --quiet HEAD openapi.yml || (git commit -m "Update bundled file" && git push)
