name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "docs/**"
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: lint
        run: npx @redocly/cli lint src/openapi.yml
      - name: bundle
        run: npx @redocly/cli bundle src/openapi.yml -o openapi.yml
      - uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi.yml

  test_openapi-typescript:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: generate type file
        run: npx openapi-typescript openapi.yml -o test/dist/openapi-typescript/schema.d.ts

  test_openapi-generator:
    needs: bundle
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-Dlog.level=warn"
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: use typescript-node generator
        run: npx @openapitools/openapi-generator-cli --openapitools test/openapitools.json generate -i openapi.yml -g typescript-node -o test/dist/openapi-generator/typescript-node
      - name: use java generator
        run: |
          npx @openapitools/openapi-generator-cli --openapitools test/openapitools.json generate -i openapi.yml -g java -o test/dist/openapi-generator/java
          cd test/dist/openapi-generator/java
          chmod +x gradlew
          ./gradlew build --warn

  build-docs:
    needs:
      - test_openapi-typescript
      - test_openapi-generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: docs
        run: cp -f openapi.yml docs/openapi.yml
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi.yml docs/openapi.yml
          git diff-index --quiet HEAD openapi.yml docs/openapi.yml || (git commit -m "Update bundle, docs" && git push)
