name: Deploy docs to GitHub Pages

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ".github/workflows/docs.yml"
      - uses: actions/configure-pages@v5
        id: setup
      - name: build docs
        run: |
          mkdir dist
          cp -r docs/assets/* dist
          npx @redocly/cli build-docs openapi.yml -t docs/custom.hbs --templateOptions.basePath "${{ steps.setup.outputs.base_path }}" -o dist/index.html
          `cat <<EOT > dist/sitemap.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
          <loc>${{ steps.setup.outputs.base_url }}/</loc>
          <lastmod>$(date +"%Y-%m-%dT%H:%M:%S%:z")</lastmod>
          </url>
          </urlset>
          EOT`
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
