name: Generate docs

on:
  push:
    paths:
      - ".github/workflows/generate-docs.yml"
      - "src/**"
      - "docs/**"
    tags-ignore:
      - "*"
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: lint
        run: npx @redocly/cli lint src/openapi.yml
      - name: bundle
        run: npx @redocly/cli bundle src/openapi.yml -o openapi.yml
      - name: docs
        run: cp -f openapi.yml docs/openapi.yml
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi.yml docs/openapi.yml
          git diff-index --quiet HEAD openapi.yml docs/openapi.yml || (git commit -m "Update bundle files, build docs" && git push)
