name: Deploy docs to Pages

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - $default-branch

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
        id: setup
      - name: test
        run: |
          `cat <<EOT > sitemap.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
          <loc>${{ steps.setup.outputs.base_url }}/</loc>
          <lastmod>$(date +"%Y-%m-%dT%H:%M:%S%:z")</lastmod>
          </url>
          </urlset>
          EOT`
          cat sitemap.xml
      # - uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "docs"

  # deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/deploy-pages@v4
  #       id: deployment
