name: Redoc

on:
  push:
    paths:
      - '.github/workflows/redoc.yml'
      - 'index.html'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: bundle
        run: docker run --rm -v $(pwd):/workspace jeanberu/swagger-cli:4.0.4 swagger-cli bundle -o workspace/openapi.yml -t yaml workspace/src/openapi.yml
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi.yml
          git diff-index --quiet HEAD openapi.yml || (git commit -m "Update bundle yaml files" && git push)
